'use strict';
// AST → JavaScript codegen. Emits, from a parsed `.lidl` module:
//   * a typed CONSUMER client (each method → an async wrapper over proxy.call;
//     each event → an on<Event>() subscription helper), and
//   * a PROVIDER scaffold (a serve(transports, impl) factory wiring handlers +
//     typed emit<Event>() helpers).
// JS is untyped, so types are surfaced as JSDoc for editor hints.

// ── lidl type → JSDoc type string ───────────────────────────────────────────
function jsdocType(t) {
  if (!t || !t.kind) return '*';
  switch (t.kind) {
    case 'primitive': {
      switch (t.name) {
        case 'int': case 'uint': case 'float64': case 'float32': return 'number';
        case 'bool': return 'boolean';
        case 'tstr': return 'string';
        case 'bstr': return '{_bytes: string}'; // base64url-in-JSON per the ABI
        case 'any': return '*';
        default: return 'number';
      }
    }
    case 'array':   return `Array<${jsdocType(t.elements && t.elements[0])}>`;
    case 'map':     return `Object<${jsdocType(t.elements && t.elements[0])}, ${jsdocType(t.elements && t.elements[1])}>`;
    case 'optional':return `(${jsdocType(t.elements && t.elements[0])}|null)`;
    case 'named':   return t.name || 'Object';
    default:        return '*';
  }
}

function pascal(name) {
  return String(name).replace(/(^|[_-])([a-z])/g, (_, __, c) => c.toUpperCase());
}
// Render a lidl type back to its source-ish syntax (for readable doc comments).
function lidlType(t) {
  if (!t || !t.kind) return '?';
  switch (t.kind) {
    case 'array':    return `[${lidlType(t.elements && t.elements[0])}]`;
    case 'map':      return `{${lidlType(t.elements && t.elements[0])}: ${lidlType(t.elements && t.elements[1])}}`;
    case 'optional': return `?${lidlType(t.elements && t.elements[0])}`;
    default:         return t.name || '?';
  }
}
const paramNames = (m) => (m.params || []).map((p) => p.name);
const sig = (m) => `${m.name}(${(m.params || []).map((p) => `${p.name}: ${lidlType(p.type)}`).join(', ')})`;
const header = (mod, kind) =>
  `// GENERATED by logos-js-sdk codegen from ${mod.name}.lidl — do not edit.\n` +
  `// ${kind} for module "${mod.name}" v${mod.version || '?'}.\n` +
  (mod.description ? `// ${mod.description}\n` : '') +
  `'use strict';\n\n`;

// ── consumer client ─────────────────────────────────────────────────────────
function generateClient(mod, { sdkImport = 'logos-js-sdk' } = {}) {
  const Cls = pascal(mod.name) + 'Client';
  let out = header(mod, 'Typed client');
  out += `class ${Cls} {\n`;
  out += `  /** @param {import('${sdkImport}').ModuleProxy} proxy */\n`;
  out += `  constructor(proxy) { this._proxy = proxy; }\n\n`;
  out += `  /** Bind against a LogosClient. @param {import('${sdkImport}').LogosClient} logos */\n`;
  out += `  static bind(logos, moduleName = ${JSON.stringify(mod.name)}) {\n`;
  out += `    return new ${Cls}(logos.module(moduleName));\n  }\n`;

  for (const m of mod.methods || []) {
    const args = paramNames(m);
    const paramDoc = (m.params || []).map((p) => `   * @param {${jsdocType(p.type)}} ${p.name}`).join('\n');
    out += `\n  /**\n   * ${sig(m)} -> ${m.returnType ? lidlType(m.returnType) : 'void'}` +
           `${m.description ? `\n   * ${m.description}` : ''}\n` +
           `${paramDoc ? paramDoc + '\n' : ''}` +
           `   * @returns {Promise<${jsdocType(m.returnType)}>}\n   */\n`;
    out += `  ${m.name}(${args.join(', ')}) {\n`;
    out += `    return this._proxy.call(${[JSON.stringify(m.name), ...args].join(', ')});\n  }\n`;
  }

  for (const e of mod.events || []) {
    const paramDoc = (e.params || []).map((p) => `   * @param {${jsdocType(p.type)}} ${p.name}`).join('\n');
    out += `\n  /**\n   * Subscribe to event ${sig(e)}.` +
           `${e.description ? `\n   * ${e.description}` : ''}\n${paramDoc ? paramDoc + '\n' : ''}` +
           `   * @param {Function} handler  called with the event payload as positional args\n` +
           `   * @returns {Function} unsubscribe\n   */\n`;
    out += `  on${pascal(e.name)}(handler) {\n`;
    out += `    return this._proxy.on(${JSON.stringify(e.name)}, handler);\n  }\n`;
  }

  out += `}\n\nmodule.exports = { ${Cls} };\n`;
  return out;
}

// -- browser client (ES module) ---------------------------------------------
//
// The SAME shape as generateClient's, emitted as an ES MODULE against the
// browser build's proxy (src/web/consumer.js) instead of the koffi one. Two
// differences, both forced by the transport and both visible in the output:
// getMethods() is a Promise there, and the module is `export class` rather than
// `module.exports`, because a browser build is loaded by an import and a
// generated file that needed a bundler to be usable would defeat the point.
//
// No runtime import is emitted. The client only ever touches the proxy it is
// handed, so an import of the SDK would be a hard dependency on WHERE the SDK
// was bundled - the specifier survives in the JSDoc types, which is where an
// editor wants it and a loader does not.
function generateWebClient(mod, { sdkImport = 'logos-js-sdk/web' } = {}) {
  const Cls = pascal(mod.name) + 'Client';
  let out = header(mod, 'Typed browser client');
  out += `class ${Cls} {\n`;
  out += `  /** @param {import('${sdkImport}').WebModuleProxy} proxy */\n`;
  out += `  constructor(proxy) { this._proxy = proxy; }\n\n`;
  out += `  /** Bind against a WebClient. @param {import('${sdkImport}').WebClient} logos */\n`;
  out += `  static bind(logos, moduleName = ${JSON.stringify(mod.name)}) {\n`;
  out += `    return new ${Cls}(logos.module(moduleName));\n  }\n`;

  for (const m of mod.methods || []) {
    const args = paramNames(m);
    const paramDoc = (m.params || []).map((p) => `   * @param {${jsdocType(p.type)}} ${p.name}`).join('\n');
    out += `\n  /**\n   * ${sig(m)} -> ${m.returnType ? lidlType(m.returnType) : 'void'}` +
           `${m.description ? `\n   * ${m.description}` : ''}\n` +
           `${paramDoc ? paramDoc + '\n' : ''}` +
           `   * @returns {Promise<${jsdocType(m.returnType)}>}\n   */\n`;
    out += `  ${m.name}(${args.join(', ')}) {\n`;
    out += `    return this._proxy.call(${[JSON.stringify(m.name), ...args].join(', ')});\n  }\n`;
  }

  for (const e of mod.events || []) {
    const paramDoc = (e.params || []).map((p) => `   * @param {${jsdocType(p.type)}} ${p.name}`).join('\n');
    out += `\n  /**\n   * Subscribe to event ${sig(e)}.` +
           `${e.description ? `\n   * ${e.description}` : ''}\n${paramDoc ? paramDoc + '\n' : ''}` +
           `   * @param {Function} handler  called with the event payload as positional args\n` +
           `   * @returns {Function} unsubscribe\n   */\n`;
    out += `  on${pascal(e.name)}(handler) {\n`;
    out += `    return this._proxy.on(${JSON.stringify(e.name)}, handler);\n  }\n`;
  }

  out += `\n  /** The module's interface as the provider reports it.\n`;
  out += `   * @returns {Promise<Array<{name: string, type: string}>>} */\n`;
  out += `  getMethods() { return this._proxy.getMethods(); }\n`;
  out += `}\n\nexport { ${Cls} };\nexport default ${Cls};\n`;
  return out;
}

// ── provider scaffold ───────────────────────────────────────────────────────
function generateProvider(mod, { sdkImport = 'logos-js-sdk' } = {}) {
  let out = header(mod, 'Provider scaffold');
  out += `const { Provider } = require(${JSON.stringify(sdkImport)});\n\n`;
  out += `// Implement each method below (synchronous — return a value, not a Promise).\n`;
  out += `// Then: const m = serve(tcp('127.0.0.1', 6001), new ${pascal(mod.name)}Impl());\n\n`;

  // an example impl class stub
  out += `class ${pascal(mod.name)}Impl {\n`;
  for (const m of mod.methods || []) {
    const args = paramNames(m);
    const paramDoc = (m.params || []).map((p) => `   * @param {${jsdocType(p.type)}} ${p.name}`).join('\n');
    out += `  /**\n   * ${sig(m)} -> ${m.returnType ? lidlType(m.returnType) : 'void'}\n` +
           `${paramDoc ? paramDoc + '\n' : ''}   * @returns {${jsdocType(m.returnType)}}\n   */\n`;
    out += `  ${m.name}(${args.join(', ')}) {\n    throw new Error('${mod.name}.${m.name} not implemented');\n  }\n`;
  }
  out += `}\n\n`;

  // the serve() factory: wires handlers + declares events, returns typed emit helpers
  out += `function serve(transports, impl) {\n`;
  out += `  const provider = new Provider(${JSON.stringify(mod.name)}, transports);\n`;
  out += `  provider.register({\n    handlers: {\n`;
  for (const m of mod.methods || []) {
    const args = paramNames(m);
    out += `      ${m.name}: (${args.join(', ')}) => impl.${m.name}(${args.join(', ')}),\n`;
  }
  out += `    },\n`;
  out += `    events: ${JSON.stringify((mod.events || []).map((e) => e.name))},\n`;
  out += `  });\n`;
  out += `  return {\n    provider,\n    stop: () => provider.destroy(),\n`;
  for (const e of mod.events || []) {
    const args = paramNames(e);
    out += `    emit${pascal(e.name)}: (${args.join(', ')}) => provider.emit(${[JSON.stringify(e.name), ...args].join(', ')}),\n`;
  }
  out += `  };\n}\n\nmodule.exports = { serve, ${pascal(mod.name)}Impl };\n`;
  return out;
}

module.exports = { generateClient, generateWebClient, generateProvider, jsdocType, pascal };
